### ISSUE TITLE
No user sign up option in the login page

### ISSUE THREAD

**Issue by prao7** [cjwilson2020/WDYWW#13]
Once you go into the log in page and enter a un-registered user, you cannot sign up as a new user nor back out to the homepage from the options. The back button doesn't work too for the app on some older Android versions so this makes not having a sign up or homepage option a challenge.

**Comment by peterdaly13** [comment]
As specified in our README document, we expect all users to have API version 29 or higher so we don't expect the lack of back button to be an issue.
