### ISSUE TITLE
unable to sycn gradle

### ISSUE THREAD

**Issue by NeutrinoLiu** [cjwilson2020/WDYWW#15]
Hi guys

After I checkout to the test branch and try to gradle sync, it threw out this error:
`2:06 AM Gradle sync failed: com.android.tools.idea.gradle.project.sync.idea.issues.SdkPlatformNotFoundException: Module: 'app' platform 'android-29' not found. (1 s 290 ms)`
any idea how to solve this?

MacOS, already built an emulator with API30

**Comment by yuanchenGH** [comment]
We can not reproduce the bug so we can not help
