### ISSUE TITLE
App does not launch on Google Pixel 2

### ISSUE THREAD

**Issue by WillDaru22** [cjwilson2020/WDYWW#16]
This might be an android studio issue but when attempting to launch the app on a Pixel 2 Emulator with API 30 the app refuses to launch with no error message given.  If this is just android studio being dumb though feel free to close this.

Severity: Low

Potential incompatibility with device but equally possible android studio is just being dumb.

**Comment by yuanchenGH** [comment]
We are able to run the app on pixel 2 emulator so we can not replicate the bug.
