### ISSUE TITLE
Log in Button does not prompt if user does not log out

### ISSUE THREAD

**Issue by WillDaru22** [cjwilson2020/WDYWW#18]
Tested on Google Pixel 3a.
If the user does not select the log out option when the app closes (due to a crash or other reason), they are logged in to the last accessed account on the device without a prompt for login.  This may be intentional but could pose a security risk if multiple users share a device.

Severity: Low/Enhancement

Suggestion:  Prompt the user for a login every time the app is opened to minimize security risks.  Very minor thing though and mostly a non-issue for devices with only one user.

**Comment by peterdaly13** [comment]
This is intentional. We believe the benefits of not needing to remember your password outweigh the potential security risk, as we do not save any sensitive user information. In the case that 2 people share a device, they maintain the option to log in and out as they please.
